// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $$0 from "./islands/ButtonMenu.tsx";
import * as $$1 from "./islands/ButtonTips.tsx";
import * as $$2 from "./islands/ModalMenu.tsx";
import * as $$3 from "./islands/request.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
  },
  islands: {
    "./islands/ButtonMenu.tsx": $$0,
    "./islands/ButtonTips.tsx": $$1,
    "./islands/ModalMenu.tsx": $$2,
    "./islands/request.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
