// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/BotBounty.tsx";
import * as $$$$$$1 from "./sections/Footer.tsx";
import * as $$$$$$2 from "./sections/Header.tsx";
import * as $$$$$$3 from "./sections/Hero.tsx";
import * as $$$$$$4 from "./sections/SimpleTextList.tsx";
import * as $$$$$$5 from "./sections/Theme.tsx";
import * as $$$$$$6 from "./sections/Tips.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "sections": {
    "deco-sites/bounty-a-la-gpt/sections/BotBounty.tsx": $$$$$$0,
    "deco-sites/bounty-a-la-gpt/sections/Footer.tsx": $$$$$$1,
    "deco-sites/bounty-a-la-gpt/sections/Header.tsx": $$$$$$2,
    "deco-sites/bounty-a-la-gpt/sections/Hero.tsx": $$$$$$3,
    "deco-sites/bounty-a-la-gpt/sections/SimpleTextList.tsx": $$$$$$4,
    "deco-sites/bounty-a-la-gpt/sections/Theme.tsx": $$$$$$5,
    "deco-sites/bounty-a-la-gpt/sections/Tips.tsx": $$$$$$6,
  },
  "apps": {
    "deco-sites/bounty-a-la-gpt/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/bounty-a-la-gpt/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/bounty-a-la-gpt",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
